### ISSUE TITLE
Realizar pesquisa de mercado sobre possíveis produtos do grupo

### ISSUE THREAD

**Issue by ericbky** [UnBArqDsw2024-2/2024.2_G3_Aprender_Entrega_01#2]
**Descrição**
------
Essa issue tem como objetivo realizar pesquisas de mercado com público-alvo sobre ideias que tivemos de possíveis produtos a serem desenvolvidos. A pesquisa deve contemplar o melhor meio necessário, podendo ser desde um formulário em grupos, quanto uma conversa com o possível cliente, porém deve ser tudo possivelmente documentável. 

**Critérios de Aceitação**
-----

- [x] Conter prós e contras sobre todos os possíveis produtos.
- [x]  Realizar um levantamento de dados com clientes (conversa, formulário...)
- [x]  Deve estar documentado toda a análise.
- [x]  Deve haver um alinhamento e decisão com todo o grupo.

**Links**
-----

Miro: https://miro.com/app/board/uXjVLQDYj8A=/

**Temas, membros, público alvo e artefatos**
-----

1. Brainly 
Membros nesse tema: Ana, Eric, Giovanni, Luiz
Público alvo: Estudantes da FGA
Artefatos: Google Forms, análise de viabilidade

2. Enem
Membros nesse tema: Arthur, Gustavo, João, Julio
Público alvo: Vestibulando do ENEM, provável cliente Prof de ensino médio
Artefatos:  Conversa com o cliente, análise de viabilidade

3. Duolingo
Membros nesse tema: Danilo, Diego, Motta, Paulo
Público alvo: Estudantes de Calculo, provável cliente Fragelli ou Maurício
Artefatos:  Conversa com o cliente, análise de viabilidade

**Comment by giovanniacg** [comment]
Se possível, adicionar na issue os detalhes da enquete no wpp onde mostra a relação de membro e tema, dando enfase em qual é o público alvo de cada tema para facilitar a pesquisa.

Além de adicionar também os artefatos que serão gerados com cada tema para que fique mais objetivo e claro para todos ao longo do tempo.

**Comment by CarolCoCe** [comment]
Adicionei um pouco disso
