### ISSUE TITLE
(Squad 3) Elaboração e Documentação do BPMN

### ISSUE THREAD

**Issue by gusrberto** [UnBArqDsw2024-2/2024.2_G3_Aprender_Entrega_01#22]
### Descricao da Tarefa

Criação de um diagrama BPMN descrevendo a metodologia utilizada pelo Squad 3, trazendo as práticas, estruturas e fluxos de trabalho adotados no processo.

### Checklist da Tarefa

- [x] Elaboração do BPMN com base nas metodologias definidas pelo Squad.
- [x] Diagrama devidamente documentado no Pages.
- [x] Consideração sobre as contribuições dos participantes do Squad.

**Comment by LuizGust4vo** [comment]
Feito.
